version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y zip

  build:
    commands:
      - echo "Build complete. Nothing to zip manually."

artifacts:
  files:
    - '**/*'
