apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels: 
    app: mysql
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/mysql"

