apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteMany

