apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.claimName }}
  labels:
    app: mysql
spec:
  storageClassName: manual
  resources:
    requests:
      storage: {{ .Values.mysql.size }}
  accessModes:
    - ReadWriteOnce
