apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels: 
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.mysql.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/mysql"

