apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: {{ .Release.Name }}-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: {{ .Values.mysql.image.name }}
        image: {{ .Values.mysql.image.name }}:{{ .Values.mysql.image.tag }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.secretName }}
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.databaseName }}
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.secretName }}
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.secretName }}
              key: MYSQL_PASSWORD
        ports:
        - containerPort: {{ .Values.mysql.port }}
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
       - name: mysql-storage
         persistentVolumeClaim:
           claimName: {{ .Values.mysql.claimName }}
