name: CI process for Gogs with cloud deploy
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    name: Testing source code Gogs
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Одержуємо код з репозиторію

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Run tests
      run: go test ./... # Запускаємо всі тести

  lint:
    name: Linting source code Gogs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2 # Одержуємо код з репозиторію

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Dowload lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Linting
      run: golangci-lint run --verbose --timeout=5m ./...
